#############################################################################
# Makefile for building: DPI_Checker
# Generated by qmake (3.1) (Qt 6.1.2)
# Project:  ../DPI_Checker/DPI_Checker.pro
# Template: app
# Command: /home/alexm/Qt/6.1.2/gcc_64/bin/qmake -o Makefile ../DPI_Checker/DPI_Checker.pro -spec linux-g++ CONFIG+=qtquickcompiler
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I../DPI_Checker -I. -I/home/alexm/Qt/6.1.2/gcc_64/include -I/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets -I/home/alexm/Qt/6.1.2/gcc_64/include/QtGui -I/home/alexm/Qt/6.1.2/gcc_64/include/QtCore -I. -I. -I/home/alexm/Qt/6.1.2/gcc_64/mkspecs/linux-g++
QMAKE         = /home/alexm/Qt/6.1.2/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/alexm/Qt/6.1.2/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/alexm/Qt/6.1.2/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = DPI_Checker1.0.0
DISTDIR = /media/alexm/data/Coding/Qt/build-DPI_Checker-Desktop_Qt_6_1_2_GCC_64bit-Release/.tmp/DPI_Checker1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/alexm/Qt/6.1.2/gcc_64/lib
LIBS          = $(SUBLIBS) /home/alexm/Qt/6.1.2/gcc_64/lib/libQt6Widgets.so /home/alexm/Qt/6.1.2/gcc_64/lib/libQt6Gui.so /home/alexm/Qt/6.1.2/gcc_64/lib/libQt6Core.so -lpthread -lGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../DPI_Checker/about.cpp \
		../DPI_Checker/faq.cpp \
		../DPI_Checker/main.cpp \
		../DPI_Checker/mainwindow.cpp \
		../DPI_Checker/mouseinfo.cpp qrc_Resources.cpp \
		moc_about.cpp \
		moc_faq.cpp \
		moc_mainwindow.cpp
OBJECTS       = about.o \
		faq.o \
		main.o \
		mainwindow.o \
		mouseinfo.o \
		qrc_Resources.o \
		moc_about.o \
		moc_faq.o \
		moc_mainwindow.o
DIST          = /home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/spec_pre.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/common/unix.conf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/common/linux.conf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/common/sanitize.conf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/common/gcc-base.conf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/common/g++-base.conf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/common/g++-unix.conf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/qconfig.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_ext_libpng.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labssettings.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_linguist.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_linguist_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_tools_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/qt_functions.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/qt_config.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/spec_post.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/toolchain.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/default_pre.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/resolve_config.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/default_post.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/qtquickcompiler.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/warn_on.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/qt.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/resources_functions.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/resources.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/moc.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/uic.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/unix/thread.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/qmake_use.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/file_copies.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/exceptions.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/yacc.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/lex.prf \
		../DPI_Checker/DPI_Checker.pro ../DPI_Checker/about.h \
		../DPI_Checker/faq.h \
		../DPI_Checker/mainwindow.h \
		../DPI_Checker/mouseinfo.h ../DPI_Checker/about.cpp \
		../DPI_Checker/faq.cpp \
		../DPI_Checker/main.cpp \
		../DPI_Checker/mainwindow.cpp \
		../DPI_Checker/mouseinfo.cpp
QMAKE_TARGET  = DPI_Checker
DESTDIR       = 
TARGET        = DPI_Checker


first: all
####### Build rules

DPI_Checker: ui_about.h ui_faq.h ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../DPI_Checker/DPI_Checker.pro /home/alexm/Qt/6.1.2/gcc_64/mkspecs/linux-g++/qmake.conf /home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/spec_pre.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/common/unix.conf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/common/linux.conf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/common/sanitize.conf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/common/gcc-base.conf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/common/g++-base.conf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/common/g++-unix.conf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/qconfig.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_ext_libpng.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labssettings.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_linguist.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_linguist_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_tools_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/qt_functions.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/qt_config.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/spec_post.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/toolchain.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/default_pre.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/resolve_config.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/default_post.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/qtquickcompiler.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/warn_on.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/qt.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/resources_functions.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/resources.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/moc.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/uic.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/unix/thread.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/qmake_use.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/file_copies.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/exceptions.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/yacc.prf \
		/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/lex.prf \
		../DPI_Checker/DPI_Checker.pro \
		../DPI_Checker/Resources.qrc \
		/home/alexm/Qt/6.1.2/gcc_64/lib/libQt6Widgets.prl \
		/home/alexm/Qt/6.1.2/gcc_64/lib/libQt6Gui.prl \
		/home/alexm/Qt/6.1.2/gcc_64/lib/libQt6Core.prl
	$(QMAKE) -o Makefile ../DPI_Checker/DPI_Checker.pro -spec linux-g++ CONFIG+=qtquickcompiler
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/spec_pre.prf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/common/unix.conf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/common/linux.conf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/common/sanitize.conf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/common/gcc-base.conf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/common/g++-base.conf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/common/g++-unix.conf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/qconfig.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_ext_libpng.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labssettings.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_linguist.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_linguist_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_tools_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/qt_functions.prf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/qt_config.prf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/spec_post.prf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/toolchain.prf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/default_pre.prf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/resolve_config.prf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/default_post.prf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/qtquickcompiler.prf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/warn_on.prf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/qt.prf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/resources_functions.prf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/resources.prf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/moc.prf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/unix/opengl.prf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/uic.prf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/unix/thread.prf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/qmake_use.prf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/file_copies.prf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/testcase_targets.prf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/exceptions.prf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/yacc.prf:
/home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/lex.prf:
../DPI_Checker/DPI_Checker.pro:
../DPI_Checker/Resources.qrc:
/home/alexm/Qt/6.1.2/gcc_64/lib/libQt6Widgets.prl:
/home/alexm/Qt/6.1.2/gcc_64/lib/libQt6Gui.prl:
/home/alexm/Qt/6.1.2/gcc_64/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../DPI_Checker/DPI_Checker.pro -spec linux-g++ CONFIG+=qtquickcompiler

qmake_all: FORCE


all: Makefile DPI_Checker

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../DPI_Checker/Resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../DPI_Checker/about.h ../DPI_Checker/faq.h ../DPI_Checker/mainwindow.h ../DPI_Checker/mouseinfo.h $(DISTDIR)/
	$(COPY_FILE) --parents ../DPI_Checker/about.cpp ../DPI_Checker/faq.cpp ../DPI_Checker/main.cpp ../DPI_Checker/mainwindow.cpp ../DPI_Checker/mouseinfo.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../DPI_Checker/about.ui ../DPI_Checker/faq.ui ../DPI_Checker/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_Resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_Resources.cpp
qrc_Resources.cpp: ../DPI_Checker/Resources.qrc \
		/home/alexm/Qt/6.1.2/gcc_64/libexec/rcc \
		../DPI_Checker/imgs/img3.png \
		../DPI_Checker/imgs/img1.png \
		../DPI_Checker/imgs/img2.png \
		../DPI_Checker/imgs/ico.ico \
		../DPI_Checker/qss/stylesheet.qss
	/home/alexm/Qt/6.1.2/gcc_64/libexec/rcc -name Resources ../DPI_Checker/Resources.qrc -o qrc_Resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /home/alexm/Qt/6.1.2/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_about.cpp moc_faq.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_about.cpp moc_faq.cpp moc_mainwindow.cpp
moc_about.cpp: ../DPI_Checker/about.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/QDialog \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qdialog.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qtguiglobal.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qglobal.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qconfig.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtcore-config.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsystemdetection.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qprocessordetection.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtypeinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsysinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qlogging.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qflags.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qatomic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbasicatomic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qgenericatomic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qglobalstatic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmutex.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qnumeric.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qversiontagging.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qtgui-config.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qwidget.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qwindowdefs.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobjectdefs.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qnamespace.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtmetamacros.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobject.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstring.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qchar.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearray.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qrefcount.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qarraydata.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpair.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qarraydatapointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qarraydataops.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearrayview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringliteral.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qanystringview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qutf8stringview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringtokenizer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringbuilder.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qlist.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qhashfunctions.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiterator.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearraylist.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringlist.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qalgorithms.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringmatcher.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcoreevent.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qscopedpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmetatype.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcompare.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qdatastream.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiodevicebase.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiterable.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmetacontainer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontainerinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtaggedpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmath.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobject_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qproperty.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qshareddata.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpropertyprivate.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmargins.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpaintdevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qrect.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsize.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpoint.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpalette.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qcolor.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qrgb.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qrgba64.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qbrush.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qimage.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpixelformat.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qtransform.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpolygon.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qregion.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qline.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpixmap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsharedpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qfont.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qfontmetrics.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qfontinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qcursor.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qbitmap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qkeysequence.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qevent.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiodevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qurl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qvariant.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qshareddata_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qhash.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qdebug.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtextstream.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringconverter.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qset.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qeventpoint.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qvector2d.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qvectornd.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpointingdevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qinputdevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qscreen.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QList \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QObject \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QRect \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QSize \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QSizeF \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/QTransform \
		moc_predefs.h \
		/home/alexm/Qt/6.1.2/gcc_64/libexec/moc
	/home/alexm/Qt/6.1.2/gcc_64/libexec/moc $(DEFINES) --include /media/alexm/data/Coding/Qt/build-DPI_Checker-Desktop_Qt_6_1_2_GCC_64bit-Release/moc_predefs.h -I/home/alexm/Qt/6.1.2/gcc_64/mkspecs/linux-g++ -I/media/alexm/data/Coding/Qt/DPI_Checker -I/home/alexm/Qt/6.1.2/gcc_64/include -I/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets -I/home/alexm/Qt/6.1.2/gcc_64/include/QtGui -I/home/alexm/Qt/6.1.2/gcc_64/include/QtCore -I. -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ../DPI_Checker/about.h -o moc_about.cpp

moc_faq.cpp: ../DPI_Checker/faq.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/QDialog \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qdialog.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qtguiglobal.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qglobal.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qconfig.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtcore-config.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsystemdetection.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qprocessordetection.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtypeinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsysinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qlogging.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qflags.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qatomic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbasicatomic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qgenericatomic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qglobalstatic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmutex.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qnumeric.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qversiontagging.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qtgui-config.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qwidget.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qwindowdefs.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobjectdefs.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qnamespace.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtmetamacros.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobject.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstring.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qchar.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearray.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qrefcount.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qarraydata.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpair.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qarraydatapointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qarraydataops.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearrayview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringliteral.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qanystringview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qutf8stringview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringtokenizer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringbuilder.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qlist.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qhashfunctions.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiterator.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearraylist.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringlist.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qalgorithms.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringmatcher.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcoreevent.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qscopedpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmetatype.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcompare.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qdatastream.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiodevicebase.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiterable.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmetacontainer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontainerinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtaggedpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmath.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobject_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qproperty.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qshareddata.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpropertyprivate.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmargins.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpaintdevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qrect.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsize.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpoint.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpalette.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qcolor.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qrgb.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qrgba64.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qbrush.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qimage.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpixelformat.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qtransform.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpolygon.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qregion.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qline.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpixmap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsharedpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qfont.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qfontmetrics.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qfontinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qcursor.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qbitmap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qkeysequence.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qevent.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiodevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qurl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qvariant.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qshareddata_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qhash.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qdebug.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtextstream.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringconverter.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qset.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qeventpoint.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qvector2d.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qvectornd.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpointingdevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qinputdevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qscreen.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QList \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QObject \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QRect \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QSize \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QSizeF \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/QTransform \
		moc_predefs.h \
		/home/alexm/Qt/6.1.2/gcc_64/libexec/moc
	/home/alexm/Qt/6.1.2/gcc_64/libexec/moc $(DEFINES) --include /media/alexm/data/Coding/Qt/build-DPI_Checker-Desktop_Qt_6_1_2_GCC_64bit-Release/moc_predefs.h -I/home/alexm/Qt/6.1.2/gcc_64/mkspecs/linux-g++ -I/media/alexm/data/Coding/Qt/DPI_Checker -I/home/alexm/Qt/6.1.2/gcc_64/include -I/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets -I/home/alexm/Qt/6.1.2/gcc_64/include/QtGui -I/home/alexm/Qt/6.1.2/gcc_64/include/QtCore -I. -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ../DPI_Checker/faq.h -o moc_faq.cpp

moc_mainwindow.cpp: ../DPI_Checker/mainwindow.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/QMainWindow \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qtguiglobal.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qglobal.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qconfig.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtcore-config.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsystemdetection.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qprocessordetection.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtypeinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsysinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qlogging.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qflags.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qatomic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbasicatomic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qgenericatomic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qglobalstatic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmutex.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qnumeric.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qversiontagging.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qtgui-config.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qwidget.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qwindowdefs.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobjectdefs.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qnamespace.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtmetamacros.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobject.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstring.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qchar.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearray.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qrefcount.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qarraydata.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpair.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qarraydatapointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qarraydataops.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearrayview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringliteral.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qanystringview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qutf8stringview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringtokenizer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringbuilder.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qlist.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qhashfunctions.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiterator.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearraylist.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringlist.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qalgorithms.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringmatcher.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcoreevent.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qscopedpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmetatype.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcompare.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qdatastream.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiodevicebase.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiterable.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmetacontainer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontainerinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtaggedpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmath.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobject_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qproperty.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qshareddata.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpropertyprivate.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmargins.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpaintdevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qrect.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsize.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpoint.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpalette.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qcolor.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qrgb.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qrgba64.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qbrush.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qimage.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpixelformat.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qtransform.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpolygon.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qregion.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qline.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpixmap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsharedpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qfont.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qfontmetrics.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qfontinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qcursor.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qbitmap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qkeysequence.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qevent.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiodevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qurl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qvariant.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qshareddata_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qhash.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qdebug.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtextstream.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringconverter.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qset.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qeventpoint.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qvector2d.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qvectornd.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpointingdevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qinputdevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qscreen.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QList \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QObject \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QRect \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QSize \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QSizeF \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/QTransform \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qicon.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QTimer \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtimer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbasictimer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/QShortcut \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qshortcut.h \
		../DPI_Checker/mouseinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QtMath \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/QCursor \
		moc_predefs.h \
		/home/alexm/Qt/6.1.2/gcc_64/libexec/moc
	/home/alexm/Qt/6.1.2/gcc_64/libexec/moc $(DEFINES) --include /media/alexm/data/Coding/Qt/build-DPI_Checker-Desktop_Qt_6_1_2_GCC_64bit-Release/moc_predefs.h -I/home/alexm/Qt/6.1.2/gcc_64/mkspecs/linux-g++ -I/media/alexm/data/Coding/Qt/DPI_Checker -I/home/alexm/Qt/6.1.2/gcc_64/include -I/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets -I/home/alexm/Qt/6.1.2/gcc_64/include/QtGui -I/home/alexm/Qt/6.1.2/gcc_64/include/QtCore -I. -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ../DPI_Checker/mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_about.h ui_faq.h ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_about.h ui_faq.h ui_mainwindow.h
ui_about.h: ../DPI_Checker/about.ui \
		/home/alexm/Qt/6.1.2/gcc_64/libexec/uic
	/home/alexm/Qt/6.1.2/gcc_64/libexec/uic ../DPI_Checker/about.ui -o ui_about.h

ui_faq.h: ../DPI_Checker/faq.ui \
		/home/alexm/Qt/6.1.2/gcc_64/libexec/uic
	/home/alexm/Qt/6.1.2/gcc_64/libexec/uic ../DPI_Checker/faq.ui -o ui_faq.h

ui_mainwindow.h: ../DPI_Checker/mainwindow.ui \
		/home/alexm/Qt/6.1.2/gcc_64/libexec/uic
	/home/alexm/Qt/6.1.2/gcc_64/libexec/uic ../DPI_Checker/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

about.o: ../DPI_Checker/about.cpp ../DPI_Checker/about.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/QDialog \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qdialog.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qtguiglobal.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qglobal.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qconfig.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtcore-config.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsystemdetection.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qprocessordetection.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtypeinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsysinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qlogging.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qflags.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qatomic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbasicatomic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qgenericatomic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qglobalstatic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmutex.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qnumeric.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qversiontagging.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qtgui-config.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qwidget.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qwindowdefs.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobjectdefs.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qnamespace.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtmetamacros.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobject.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstring.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qchar.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearray.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qrefcount.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qarraydata.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpair.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qarraydatapointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qarraydataops.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearrayview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringliteral.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qanystringview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qutf8stringview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringtokenizer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringbuilder.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qlist.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qhashfunctions.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiterator.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearraylist.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringlist.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qalgorithms.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringmatcher.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcoreevent.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qscopedpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmetatype.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcompare.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qdatastream.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiodevicebase.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiterable.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmetacontainer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontainerinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtaggedpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmath.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobject_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qproperty.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qshareddata.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpropertyprivate.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmargins.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpaintdevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qrect.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsize.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpoint.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpalette.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qcolor.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qrgb.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qrgba64.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qbrush.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qimage.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpixelformat.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qtransform.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpolygon.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qregion.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qline.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpixmap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsharedpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qfont.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qfontmetrics.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qfontinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qcursor.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qbitmap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qkeysequence.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qevent.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiodevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qurl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qvariant.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qshareddata_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qhash.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qdebug.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtextstream.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringconverter.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qset.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qeventpoint.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qvector2d.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qvectornd.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpointingdevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qinputdevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qscreen.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QList \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QObject \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QRect \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QSize \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QSizeF \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/QTransform \
		ui_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o ../DPI_Checker/about.cpp

faq.o: ../DPI_Checker/faq.cpp ../DPI_Checker/faq.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/QDialog \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qdialog.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qtguiglobal.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qglobal.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qconfig.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtcore-config.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsystemdetection.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qprocessordetection.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtypeinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsysinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qlogging.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qflags.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qatomic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbasicatomic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qgenericatomic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qglobalstatic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmutex.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qnumeric.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qversiontagging.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qtgui-config.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qwidget.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qwindowdefs.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobjectdefs.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qnamespace.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtmetamacros.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobject.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstring.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qchar.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearray.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qrefcount.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qarraydata.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpair.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qarraydatapointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qarraydataops.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearrayview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringliteral.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qanystringview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qutf8stringview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringtokenizer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringbuilder.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qlist.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qhashfunctions.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiterator.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearraylist.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringlist.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qalgorithms.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringmatcher.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcoreevent.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qscopedpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmetatype.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcompare.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qdatastream.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiodevicebase.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiterable.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmetacontainer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontainerinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtaggedpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmath.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobject_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qproperty.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qshareddata.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpropertyprivate.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmargins.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpaintdevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qrect.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsize.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpoint.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpalette.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qcolor.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qrgb.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qrgba64.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qbrush.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qimage.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpixelformat.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qtransform.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpolygon.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qregion.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qline.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpixmap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsharedpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qfont.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qfontmetrics.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qfontinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qcursor.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qbitmap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qkeysequence.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qevent.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiodevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qurl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qvariant.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qshareddata_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qhash.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qdebug.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtextstream.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringconverter.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qset.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qeventpoint.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qvector2d.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qvectornd.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpointingdevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qinputdevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qscreen.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QList \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QObject \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QRect \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QSize \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QSizeF \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/QTransform \
		ui_faq.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o faq.o ../DPI_Checker/faq.cpp

main.o: ../DPI_Checker/main.cpp ../DPI_Checker/mainwindow.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/QMainWindow \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qtguiglobal.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qglobal.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qconfig.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtcore-config.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsystemdetection.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qprocessordetection.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtypeinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsysinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qlogging.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qflags.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qatomic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbasicatomic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qgenericatomic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qglobalstatic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmutex.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qnumeric.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qversiontagging.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qtgui-config.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qwidget.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qwindowdefs.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobjectdefs.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qnamespace.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtmetamacros.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobject.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstring.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qchar.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearray.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qrefcount.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qarraydata.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpair.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qarraydatapointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qarraydataops.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearrayview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringliteral.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qanystringview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qutf8stringview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringtokenizer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringbuilder.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qlist.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qhashfunctions.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiterator.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearraylist.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringlist.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qalgorithms.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringmatcher.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcoreevent.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qscopedpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmetatype.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcompare.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qdatastream.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiodevicebase.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiterable.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmetacontainer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontainerinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtaggedpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmath.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobject_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qproperty.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qshareddata.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpropertyprivate.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmargins.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpaintdevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qrect.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsize.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpoint.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpalette.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qcolor.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qrgb.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qrgba64.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qbrush.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qimage.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpixelformat.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qtransform.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpolygon.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qregion.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qline.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpixmap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsharedpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qfont.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qfontmetrics.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qfontinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qcursor.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qbitmap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qkeysequence.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qevent.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiodevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qurl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qvariant.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qshareddata_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qhash.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qdebug.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtextstream.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringconverter.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qset.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qeventpoint.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qvector2d.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qvectornd.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpointingdevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qinputdevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qscreen.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QList \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QObject \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QRect \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QSize \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QSizeF \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/QTransform \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qicon.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QTimer \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtimer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbasictimer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/QShortcut \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qshortcut.h \
		../DPI_Checker/mouseinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QtMath \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/QCursor \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/QApplication \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qapplication.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcoreapplication.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qeventloop.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qguiapplication.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qinputmethod.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qlocale.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QFile \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qfile.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qfiledevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../DPI_Checker/main.cpp

mainwindow.o: ../DPI_Checker/mainwindow.cpp ../DPI_Checker/mainwindow.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/QMainWindow \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qtguiglobal.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qglobal.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qconfig.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtcore-config.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsystemdetection.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qprocessordetection.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtypeinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsysinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qlogging.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qflags.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qatomic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbasicatomic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qgenericatomic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qglobalstatic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmutex.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qnumeric.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qversiontagging.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qtgui-config.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qwidget.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qwindowdefs.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobjectdefs.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qnamespace.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtmetamacros.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobject.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstring.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qchar.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearray.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qrefcount.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qarraydata.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpair.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qarraydatapointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qarraydataops.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearrayview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringliteral.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qanystringview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qutf8stringview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringtokenizer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringbuilder.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qlist.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qhashfunctions.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiterator.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearraylist.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringlist.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qalgorithms.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringmatcher.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcoreevent.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qscopedpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmetatype.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcompare.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qdatastream.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiodevicebase.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiterable.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmetacontainer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontainerinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtaggedpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmath.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobject_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qproperty.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qshareddata.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpropertyprivate.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmargins.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpaintdevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qrect.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsize.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpoint.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpalette.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qcolor.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qrgb.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qrgba64.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qbrush.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qimage.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpixelformat.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qtransform.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpolygon.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qregion.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qline.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpixmap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsharedpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qfont.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qfontmetrics.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qfontinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qcursor.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qbitmap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qkeysequence.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qevent.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiodevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qurl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qvariant.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qshareddata_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qhash.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qdebug.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtextstream.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringconverter.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qset.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qeventpoint.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qvector2d.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qvectornd.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpointingdevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qinputdevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qscreen.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QList \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QObject \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QRect \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QSize \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QSizeF \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/QTransform \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qicon.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QTimer \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtimer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbasictimer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/QShortcut \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qshortcut.h \
		../DPI_Checker/mouseinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QtMath \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/QCursor \
		ui_mainwindow.h \
		../DPI_Checker/about.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/QDialog \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtWidgets/qdialog.h \
		../DPI_Checker/faq.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../DPI_Checker/mainwindow.cpp

mouseinfo.o: ../DPI_Checker/mouseinfo.cpp ../DPI_Checker/mouseinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QTimer \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtimer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qglobal.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qconfig.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtcore-config.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsystemdetection.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qprocessordetection.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtypeinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsysinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qlogging.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qflags.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qatomic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbasicatomic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qgenericatomic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qglobalstatic.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmutex.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qnumeric.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qversiontagging.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbasictimer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qnamespace.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtmetamacros.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobject.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobjectdefs.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstring.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qchar.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearray.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qrefcount.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qarraydata.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpair.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qarraydatapointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qarraydataops.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearrayview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringliteral.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qanystringview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qutf8stringview.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringtokenizer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringbuilder.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qlist.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qhashfunctions.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiterator.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qbytearraylist.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringlist.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qalgorithms.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qstringmatcher.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcoreevent.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qscopedpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmetatype.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcompare.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qdatastream.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiodevicebase.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qiterable.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmetacontainer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qcontainerinfo.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qtaggedpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmath.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qobject_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qproperty.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qshareddata.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpropertyprivate.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/QtMath \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/QCursor \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qcursor.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qtguiglobal.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qtgui-config.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qpoint.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qwindowdefs.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qbitmap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpixmap.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpaintdevice.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qrect.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qmargins.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsize.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qcolor.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qrgb.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qrgba64.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsharedpointer.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qimage.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpixelformat.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qtransform.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qpolygon.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtGui/qregion.h \
		/home/alexm/Qt/6.1.2/gcc_64/include/QtCore/qline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mouseinfo.o ../DPI_Checker/mouseinfo.cpp

qrc_Resources.o: qrc_Resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Resources.o qrc_Resources.cpp

moc_about.o: moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o moc_about.cpp

moc_faq.o: moc_faq.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_faq.o moc_faq.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/DPI_Checker/bin || mkdir -p $(INSTALL_ROOT)/opt/DPI_Checker/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/DPI_Checker/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/DPI_Checker/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/DPI_Checker/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/DPI_Checker/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

